@host = https://localhost
@port = 7072
@HouseCostMonitor.API_HostAddress = {{host}}:{{port}}

POST {{HouseCostMonitor.API_HostAddress}}/api/user/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "zaq1@WSX"
}

###
